[2016-12-03 17:08:27] DEBUG [django.db.backends:90] (0.005) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-12-03 17:08:27] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-12-03 17:12:18] DEBUG [django.db.backends:90] (0.030) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."expire_date" > '2016-12-03 22:12:18.159573' AND "django_session"."session_key" = 'ctyrbouy3oohdousc8py71pl91qwpht5'); args=('2016-12-03 22:12:18.159573', 'ctyrbouy3oohdousc8py71pl91qwpht5')
[2016-12-03 17:12:18] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = '01e659bc77a5436f9fc859d23a77e6aa'; args=('01e659bc77a5436f9fc859d23a77e6aa',)
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'None': None, 'False': False, 'True': True}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x045116A8>>, 'user': <SimpleLazyObject: <User: admin>>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40, 'INFO': 20, 'DEBUG': 10}, 'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x045104D0>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04804230>}, {}, {'LANGUAGE_CODE': 'es', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759C10>, 'LANGUAGE_BIDI': False, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E6F0>, 'app_url': '/admin/auth/', 'models': [{'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2530>, 'object_name': 'Group', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D50>, 'object_name': 'Permission', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C30>, 'object_name': 'HierarchyType', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2F70>, 'object_name': 'Hierarchy', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2FD0>, 'object_name': 'Menu', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D70>, 'object_name': 'Person', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2BB0>, 'object_name': 'UserHierarchyGroup', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D10>, 'object_name': 'UserHierarchyPermission', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C10>, 'object_name': 'User', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7CD0>, 'object_name': 'AccessToken', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C90>, 'object_name': 'Application', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0448BB30>, 'object_name': 'Grant', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2F90>, 'object_name': 'RefreshToken', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E830>, 'app_url': '/admin/contenttypes/', 'models': [{'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04510170>, 'object_name': 'ContentType', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'topico2', 'name': 'Topico2', 'app_url': '/admin/topico2/', 'models': [{'add_url': '/admin/topico2/antecedentemedico/add/', 'admin_url': '/admin/topico2/antecedentemedico/', 'name': 'Antecedentemedicos', 'object_name': 'Antecedentemedico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/consulta/add/', 'admin_url': '/admin/topico2/consulta/', 'name': 'Consultas', 'object_name': 'Consulta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/departamento/add/', 'admin_url': '/admin/topico2/departamento/', 'name': 'Departamentos', 'object_name': 'Departamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/derivacion/add/', 'admin_url': '/admin/topico2/derivacion/', 'name': 'Derivacions', 'object_name': 'Derivacion', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/diagnostico/add/', 'admin_url': '/admin/topico2/diagnostico/', 'name': 'Diagnosticos', 'object_name': 'Diagnostico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/especificacionreceta/add/', 'admin_url': '/admin/topico2/especificacionreceta/', 'name': 'EspecificacionRecetas', 'object_name': 'EspecificacionReceta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/funcionvital/add/', 'admin_url': '/admin/topico2/funcionvital/', 'name': 'Funcionvitals', 'object_name': 'Funcionvital', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/historia/add/', 'admin_url': '/admin/topico2/historia/', 'name': 'Historias', 'object_name': 'Historia', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/medicamento/add/', 'admin_url': '/admin/topico2/medicamento/', 'name': 'Medicamentos', 'object_name': 'Medicamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/paciente/add/', 'admin_url': '/admin/topico2/paciente/', 'name': 'Pacientes', 'object_name': 'Paciente', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/tratamiento/add/', 'admin_url': '/admin/topico2/tratamiento/', 'name': 'Tratamientos', 'object_name': 'Tratamiento', 'perms': {'change': True, 'add': True, 'delete': True}}]}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759CD0>, 'has_permission': True, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759C70>, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E6F0>, 'app_url': '/admin/auth/', 'models': [{'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B90>, 'object_name': 'Group', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7DD0>, 'object_name': 'Permission', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D77D0>, 'object_name': 'HierarchyType', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B30>, 'object_name': 'Hierarchy', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7F30>, 'object_name': 'Menu', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7770>, 'object_name': 'Person', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7FF0>, 'object_name': 'UserHierarchyGroup', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7810>, 'object_name': 'UserHierarchyPermission', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7D10>, 'object_name': 'User', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7CF0>, 'object_name': 'AccessToken', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7FB0>, 'object_name': 'Application', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7BF0>, 'object_name': 'Grant', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7DB0>, 'object_name': 'RefreshToken', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E830>, 'app_url': '/admin/contenttypes/', 'models': [{'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B10>, 'object_name': 'ContentType', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'topico2', 'name': 'Topico2', 'app_url': '/admin/topico2/', 'models': [{'add_url': '/admin/topico2/antecedentemedico/add/', 'admin_url': '/admin/topico2/antecedentemedico/', 'name': 'Antecedentemedicos', 'object_name': 'Antecedentemedico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/consulta/add/', 'admin_url': '/admin/topico2/consulta/', 'name': 'Consultas', 'object_name': 'Consulta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/departamento/add/', 'admin_url': '/admin/topico2/departamento/', 'name': 'Departamentos', 'object_name': 'Departamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/derivacion/add/', 'admin_url': '/admin/topico2/derivacion/', 'name': 'Derivacions', 'object_name': 'Derivacion', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/diagnostico/add/', 'admin_url': '/admin/topico2/diagnostico/', 'name': 'Diagnosticos', 'object_name': 'Diagnostico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/especificacionreceta/add/', 'admin_url': '/admin/topico2/especificacionreceta/', 'name': 'EspecificacionRecetas', 'object_name': 'EspecificacionReceta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/funcionvital/add/', 'admin_url': '/admin/topico2/funcionvital/', 'name': 'Funcionvitals', 'object_name': 'Funcionvital', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/historia/add/', 'admin_url': '/admin/topico2/historia/', 'name': 'Historias', 'object_name': 'Historia', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/medicamento/add/', 'admin_url': '/admin/topico2/medicamento/', 'name': 'Medicamentos', 'object_name': 'Medicamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/paciente/add/', 'admin_url': '/admin/topico2/paciente/', 'name': 'Pacientes', 'object_name': 'Paciente', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/tratamiento/add/', 'admin_url': '/admin/topico2/tratamiento/', 'name': 'Tratamientos', 'object_name': 'Tratamiento', 'perms': {'change': True, 'add': True, 'delete': True}}]}]}]"
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'None': None, 'False': False, 'True': True}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x045116A8>>, 'user': <SimpleLazyObject: <User: admin>>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40, 'INFO': 20, 'DEBUG': 10}, 'request': <WSGIRequest: GET '/admin/'>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x045104D0>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x04804230>}, {}, {'LANGUAGE_CODE': 'es', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759C10>, 'LANGUAGE_BIDI': False, 'app_list': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E6F0>, 'app_url': '/admin/auth/', 'models': [{'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2530>, 'object_name': 'Group', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D50>, 'object_name': 'Permission', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C30>, 'object_name': 'HierarchyType', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2F70>, 'object_name': 'Hierarchy', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2FD0>, 'object_name': 'Menu', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D70>, 'object_name': 'Person', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2BB0>, 'object_name': 'UserHierarchyGroup', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2D10>, 'object_name': 'UserHierarchyPermission', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C10>, 'object_name': 'User', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7CD0>, 'object_name': 'AccessToken', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2C90>, 'object_name': 'Application', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0448BB30>, 'object_name': 'Grant', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044B2F90>, 'object_name': 'RefreshToken', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E830>, 'app_url': '/admin/contenttypes/', 'models': [{'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x04510170>, 'object_name': 'ContentType', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'topico2', 'name': 'Topico2', 'app_url': '/admin/topico2/', 'models': [{'add_url': '/admin/topico2/antecedentemedico/add/', 'admin_url': '/admin/topico2/antecedentemedico/', 'name': 'Antecedentemedicos', 'object_name': 'Antecedentemedico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/consulta/add/', 'admin_url': '/admin/topico2/consulta/', 'name': 'Consultas', 'object_name': 'Consulta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/departamento/add/', 'admin_url': '/admin/topico2/departamento/', 'name': 'Departamentos', 'object_name': 'Departamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/derivacion/add/', 'admin_url': '/admin/topico2/derivacion/', 'name': 'Derivacions', 'object_name': 'Derivacion', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/diagnostico/add/', 'admin_url': '/admin/topico2/diagnostico/', 'name': 'Diagnosticos', 'object_name': 'Diagnostico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/especificacionreceta/add/', 'admin_url': '/admin/topico2/especificacionreceta/', 'name': 'EspecificacionRecetas', 'object_name': 'EspecificacionReceta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/funcionvital/add/', 'admin_url': '/admin/topico2/funcionvital/', 'name': 'Funcionvitals', 'object_name': 'Funcionvital', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/historia/add/', 'admin_url': '/admin/topico2/historia/', 'name': 'Historias', 'object_name': 'Historia', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/medicamento/add/', 'admin_url': '/admin/topico2/medicamento/', 'name': 'Medicamentos', 'object_name': 'Medicamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/paciente/add/', 'admin_url': '/admin/topico2/paciente/', 'name': 'Pacientes', 'object_name': 'Paciente', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/tratamiento/add/', 'admin_url': '/admin/topico2/tratamiento/', 'name': 'Tratamientos', 'object_name': 'Tratamiento', 'perms': {'change': True, 'add': True, 'delete': True}}]}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759CD0>, 'has_permission': True, 'site_url': '/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03759C70>, 'available_apps': [{'has_module_perms': True, 'app_label': 'auth', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E6F0>, 'app_url': '/admin/auth/', 'models': [{'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B90>, 'object_name': 'Group', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7DD0>, 'object_name': 'Permission', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'auths', 'name': 'Auths', 'app_url': '/admin/auths/', 'models': [{'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D77D0>, 'object_name': 'HierarchyType', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B30>, 'object_name': 'Hierarchy', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7F30>, 'object_name': 'Menu', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7770>, 'object_name': 'Person', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7FF0>, 'object_name': 'UserHierarchyGroup', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7810>, 'object_name': 'UserHierarchyPermission', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7D10>, 'object_name': 'User', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'oauth2_provider', 'name': 'Django OAuth Toolkit', 'app_url': '/admin/oauth2_provider/', 'models': [{'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7CF0>, 'object_name': 'AccessToken', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7FB0>, 'object_name': 'Application', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7BF0>, 'object_name': 'Grant', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7DB0>, 'object_name': 'RefreshToken', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'contenttypes', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x0376E830>, 'app_url': '/admin/contenttypes/', 'models': [{'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x044D7B10>, 'object_name': 'ContentType', 'perms': {'change': True, 'add': True, 'delete': True}}]}, {'has_module_perms': True, 'app_label': 'topico2', 'name': 'Topico2', 'app_url': '/admin/topico2/', 'models': [{'add_url': '/admin/topico2/antecedentemedico/add/', 'admin_url': '/admin/topico2/antecedentemedico/', 'name': 'Antecedentemedicos', 'object_name': 'Antecedentemedico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/consulta/add/', 'admin_url': '/admin/topico2/consulta/', 'name': 'Consultas', 'object_name': 'Consulta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/departamento/add/', 'admin_url': '/admin/topico2/departamento/', 'name': 'Departamentos', 'object_name': 'Departamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/derivacion/add/', 'admin_url': '/admin/topico2/derivacion/', 'name': 'Derivacions', 'object_name': 'Derivacion', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/diagnostico/add/', 'admin_url': '/admin/topico2/diagnostico/', 'name': 'Diagnosticos', 'object_name': 'Diagnostico', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/especificacionreceta/add/', 'admin_url': '/admin/topico2/especificacionreceta/', 'name': 'EspecificacionRecetas', 'object_name': 'EspecificacionReceta', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/funcionvital/add/', 'admin_url': '/admin/topico2/funcionvital/', 'name': 'Funcionvitals', 'object_name': 'Funcionvital', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/historia/add/', 'admin_url': '/admin/topico2/historia/', 'name': 'Historias', 'object_name': 'Historia', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/medicamento/add/', 'admin_url': '/admin/topico2/medicamento/', 'name': 'Medicamentos', 'object_name': 'Medicamento', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/paciente/add/', 'admin_url': '/admin/topico2/paciente/', 'name': 'Pacientes', 'object_name': 'Paciente', 'perms': {'change': True, 'add': True, 'delete': True}}, {'add_url': '/admin/topico2/tratamiento/add/', 'admin_url': '/admin/topico2/tratamiento/', 'name': 'Tratamientos', 'object_name': 'Tratamiento', 'perms': {'change': True, 'add': True, 'delete': True}}]}]}]"
[2016-12-03 17:12:18] DEBUG [django.db.backends:90] (0.044) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auths_user" ON ("django_admin_log"."user_id" = "auths_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = '01e659bc77a5436f9fc859d23a77e6aa' ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=('01e659bc77a5436f9fc859d23a77e6aa',)
[2016-12-03 17:12:18] INFO [django.server:131] "GET /admin/ HTTP/1.1" 200 17348
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/css/base.css HTTP/1.1" 200 15937
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[2016-12-03 17:12:18] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\\\pru\\\\topico\\\\ve_medicfast\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'D:\\\\pru\\\\topico\\\\ve_medicfast\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\\\pru\\\\topico\\\\ve_medicfast\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\\\pru\\\\topico\\\\medicfastv2_service\\\\medicfastv2_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2016-12-03 17:12:18] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'D:\\pru\\topico\\ve_medicfast\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'medicfastv2_service_apps.auths_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\pru\\topico\\medicfastv2_service\\medicfastv2_service_apps\\topico2_api\\urls.py'> (None:None) ^api/topico2/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pru\topico\ve_medicfast\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'medicfastv2_service_apps.topico2_api.urls' from 'D:\\\\pru\\\\topico\\\\medicfastv2_service\\\\medicfastv2_service_apps\\\\topico2_api\\\\urls.py'> (None:None) ^api/topico2/>"
[2016-12-03 17:12:18] WARNING [django.request:152] Not Found: /favicon.ico
[2016-12-03 17:12:18] WARNING [django.server:131] "GET /favicon.ico HTTP/1.1" 404 2494
[2016-12-04 06:28:20] DEBUG [django.db.backends:90] (0.003) SELECT "auths_menu"."router_json" FROM "auths_menu" ORDER BY "auths_menu"."pos" ASC; args=()
[2016-12-04 06:28:20] INFO [django.server:131] "GET /api/auths/routers/ HTTP/1.1" 200 2
[2016-12-04 06:28:29] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_application" WHERE "oauth2_provider_application"."client_id" = 'XHJWk31Fzj0uLmx49TZ8zJ1Dti31HAUTKrPNuf65'; args=('XHJWk31Fzj0uLmx49TZ8zJ1Dti31HAUTKrPNuf65',)
[2016-12-04 06:28:29] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."username" = 'admin'; args=('admin',)
[2016-12-04 06:28:30] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-12-04 06:28:30] DEBUG [django.db.backends:90] (0.008) INSERT INTO "oauth2_provider_accesstoken" ("user_id", "token", "application_id", "expires", "scope") VALUES ('01e659bc77a5436f9fc859d23a77e6aa', 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD', 1, '2016-12-04 21:28:30.007473', 'read write'); args=['01e659bc77a5436f9fc859d23a77e6aa', 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD', 1, '2016-12-04 21:28:30.007473', 'read write']
[2016-12-04 06:28:30] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-12-04 06:28:30] DEBUG [django.db.backends:90] (0.017) INSERT INTO "oauth2_provider_refreshtoken" ("user_id", "token", "application_id", "access_token_id") VALUES ('01e659bc77a5436f9fc859d23a77e6aa', 'Wg3KpKGfVdYcFL8zgqgwyEX2zWzkCr', 1, 24); args=['01e659bc77a5436f9fc859d23a77e6aa', 'Wg3KpKGfVdYcFL8zgqgwyEX2zWzkCr', 1, 24]
[2016-12-04 06:28:30] INFO [django.server:131] "POST /o/token/ HTTP/1.1" 200 169
[2016-12-04 06:28:32] INFO [django.server:131] "OPTIONS /api/auths/localuserinfo/ HTTP/1.1" 200 0
[2016-12-04 06:28:32] INFO [django.server:131] "OPTIONS /api/auths/usermenu/ HTTP/1.1" 200 0
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.003) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.004) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.003) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = '7engapu9im57utnmi7go43wv2688ioem' LIMIT 1; args=('7engapu9im57utnmi7go43wv2688ioem',)
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.010) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT '7engapu9im57utnmi7go43wv2688ioem', 'ZWMyMmE2MTA1MzM3NDcxZTRmYzk5YzliZTNiYjg2ZTZkMjFlMTc0NTp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-12-04 11:29:02.552096'; args=('7engapu9im57utnmi7go43wv2688ioem', 'ZWMyMmE2MTA1MzM3NDcxZTRmYzk5YzliZTNiYjg2ZTZkMjFlMTc0NTp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-12-04 11:29:02.552096')
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = '01e659bc77a5436f9fc859d23a77e6aa'; args=('01e659bc77a5436f9fc859d23a77e6aa',)
[2016-12-04 06:28:32] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-12-04 06:28:32] DEBUG [django.db.backends:90] (0.280) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = '01e659bc77a5436f9fc859d23a77e6aa' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('01e659bc77a5436f9fc859d23a77e6aa',)
[2016-12-04 06:28:32] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 405
[2016-12-04 06:28:40] INFO [django.server:131] "OPTIONS /api/topico2/historias/ HTTP/1.1" 200 0
[2016-12-04 06:28:40] DEBUG [django.db.backends:90] (0.004) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:40] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:40] DEBUG [django.db.backends:90] (0.016) SELECT "topico2_historia"."id", "topico2_historia"."numero", "topico2_historia"."atencion", "topico2_historia"."estado", "topico2_historia"."paciente_id", "topico2_historia"."antecedentemedico_id", "topico2_historia"."usuario_id", "topico2_historia"."created_at", "topico2_historia"."updated_at" FROM "topico2_historia"; args=()
[2016-12-04 06:28:40] INFO [django.server:131] "GET /api/topico2/historias/ HTTP/1.1" 200 405
[2016-12-04 06:28:41] INFO [django.server:131] "OPTIONS /api/topico2/consultas/ HTTP/1.1" 200 0
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.001) SELECT "topico2_consulta"."id", "topico2_consulta"."historia_id", "topico2_consulta"."enfermedadactual", "topico2_consulta"."examenfisico", "topico2_consulta"."funcionvital_id", "topico2_consulta"."fecha", "topico2_consulta"."suministrar", "topico2_consulta"."estado", "topico2_consulta"."user_id" FROM "topico2_consulta"; args=()
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.001) SELECT "topico2_diagnostico"."id", "topico2_diagnostico"."codigo", "topico2_diagnostico"."nombre" FROM "topico2_diagnostico" INNER JOIN "topico2_consulta_diagnostico" ON ("topico2_diagnostico"."id" = "topico2_consulta_diagnostico"."diagnostico_id") WHERE "topico2_consulta_diagnostico"."consulta_id" = 1; args=(1,)
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.000) SELECT "topico2_diagnostico"."id", "topico2_diagnostico"."codigo", "topico2_diagnostico"."nombre" FROM "topico2_diagnostico" INNER JOIN "topico2_consulta_diagnostico" ON ("topico2_diagnostico"."id" = "topico2_consulta_diagnostico"."diagnostico_id") WHERE "topico2_consulta_diagnostico"."consulta_id" = 2; args=(2,)
[2016-12-04 06:28:41] DEBUG [django.db.backends:90] (0.000) SELECT "topico2_diagnostico"."id", "topico2_diagnostico"."codigo", "topico2_diagnostico"."nombre" FROM "topico2_diagnostico" INNER JOIN "topico2_consulta_diagnostico" ON ("topico2_diagnostico"."id" = "topico2_consulta_diagnostico"."diagnostico_id") WHERE "topico2_consulta_diagnostico"."consulta_id" = 3; args=(3,)
[2016-12-04 06:28:41] INFO [django.server:131] "GET /api/topico2/consultas/ HTTP/1.1" 200 633
[2016-12-04 06:28:43] INFO [django.server:131] "OPTIONS /api/topico2/tratamientos/ HTTP/1.1" 200 0
[2016-12-04 06:28:43] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:43] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:43] DEBUG [django.db.backends:90] (0.000) SELECT "topico2_tratamiento"."id", "topico2_tratamiento"."consulta_id", "topico2_tratamiento"."diagnostico", "topico2_tratamiento"."periododescanso", "topico2_tratamiento"."fecha", "topico2_tratamiento"."citafecha", "topico2_tratamiento"."aministracion", "topico2_tratamiento"."user_id" FROM "topico2_tratamiento"; args=()
[2016-12-04 06:28:43] INFO [django.server:131] "GET /api/topico2/tratamientos/ HTTP/1.1" 200 2
[2016-12-04 06:28:44] INFO [django.server:131] "OPTIONS /api/topico2/especificacionrecetas/ HTTP/1.1" 200 0
[2016-12-04 06:28:44] DEBUG [django.db.backends:90] (0.004) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:44] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:44] DEBUG [django.db.backends:90] (0.001) SELECT "topico2_especificacionreceta"."id", "topico2_especificacionreceta"."tratamiento_id", "topico2_especificacionreceta"."medicamento_id", "topico2_especificacionreceta"."cantidad", "topico2_especificacionreceta"."dosis", "topico2_especificacionreceta"."periodo", "topico2_especificacionreceta"."recomendacion", "topico2_especificacionreceta"."importe", "topico2_especificacionreceta"."precio_venta", "topico2_especificacionreceta"."created_at", "topico2_especificacionreceta"."updated_at" FROM "topico2_especificacionreceta"; args=()
[2016-12-04 06:28:44] INFO [django.server:131] "GET /api/topico2/especificacionrecetas/ HTTP/1.1" 200 2
[2016-12-04 06:28:59] INFO [django.server:131] "OPTIONS /api/topico2/medicamentos/ HTTP/1.1" 200 0
[2016-12-04 06:28:59] DEBUG [django.db.backends:90] (0.003) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:59] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:28:59] DEBUG [django.db.backends:90] (0.000) SELECT "topico2_medicamento"."id", "topico2_medicamento"."nombre", "topico2_medicamento"."preciocompra", "topico2_medicamento"."stock", "topico2_medicamento"."fecha", "topico2_medicamento"."tipo", "topico2_medicamento"."created_at", "topico2_medicamento"."updated_at" FROM "topico2_medicamento"; args=()
[2016-12-04 06:28:59] INFO [django.server:131] "GET /api/topico2/medicamentos/ HTTP/1.1" 200 616
[2016-12-04 06:29:00] INFO [django.server:131] "OPTIONS /api/topico2/diagnosticos/ HTTP/1.1" 200 0
[2016-12-04 06:29:00] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:29:00] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:29:00] DEBUG [django.db.backends:90] (0.001) SELECT "topico2_diagnostico"."id", "topico2_diagnostico"."codigo", "topico2_diagnostico"."nombre" FROM "topico2_diagnostico"; args=()
[2016-12-04 06:29:00] INFO [django.server:131] "GET /api/topico2/diagnosticos/ HTTP/1.1" 200 799
[2016-12-04 06:29:02] INFO [django.server:131] "OPTIONS /api/auths/permissions/ HTTP/1.1" 200 0
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'TJs1tVIXGvUQF45QbJNTD9OUuyD1LD'; args=('TJs1tVIXGvUQF45QbJNTD9OUuyD1LD',)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT COUNT(*) AS "__count" FROM "auth_permission"; args=()
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" LIMIT 5; args=()
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."id" = 1; args=(1,)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."id" = 1; args=(1,)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."id" = 1; args=(1,)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."id" = 2; args=(2,)
[2016-12-04 06:29:02] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."id" = 2; args=(2,)
[2016-12-04 06:29:02] INFO [django.server:131] "GET /api/auths/permissions/ HTTP/1.1" 200 776
